document.getElementById("reportForm").addEventListener("submit", function (e) {
  e.preventDefault();

  const cnic = document.getElementById("searchCnic").value.trim();
  const reports = JSON.parse(localStorage.getItem("reports")) || [];
  const resultDiv = document.getElementById("reportResult");

  const patientReports = reports.filter(r => r.cnic === cnic);

  if (patientReports.length === 0) {
    resultDiv.innerHTML = "<p>❌ No report found for this CNIC.</p>";
    return;
  }

  let html = "<ul>";
  patientReports.forEach(r => {
    html += `
      <li>
        <strong>${r.name}</strong> (${r.test} - ${r.department})  
        <br> 🧾 Report: ${r.result}
        <br><button onclick="downloadReport('${r.name}','${r.cnic}','${r.test}','${r.department}','${r.result}')">⬇ Download</button>
      </li>
    `;
  });
  html += "</ul>";

  resultDiv.innerHTML = html;
});

// ✅ Download Report as Text File
function downloadReport(name, cnic, test, department, result) {
  const content = `🏥 MedLab Report
-----------------------
Patient: ${name}
CNIC: ${cnic}
Department: ${department}
Test: ${test}
-----------------------
Result:
${result}
-----------------------
Generated by MedLab`;

  const blob = new Blob([content], { type: "text/plain" });
  const link = document.createElement("a");
  link.href = URL.createObjectURL(blob);
  link.download = `${name}-${test}-report.txt`;
  link.click();
}
