/* ======================================
   reports.js - Reports & Export Module
   Shows Completed Test Reports
====================================== */

document.addEventListener("DOMContentLoaded", () => {
  loadReports();
  initExportButton();
});

/* ==============================
   LOAD COMPLETED REPORTS
============================== */
function loadReports() {
  const tableBody = document.getElementById("reports-table-body");
  if (!tableBody) return;

  tableBody.innerHTML = "";
  const patients = JSON.parse(localStorage.getItem("patients")) || [];

  patients.forEach((patient) => {
    patient.tests.forEach((test) => {
      if (test.status === "Completed") {
        const row = document.createElement("tr");

        row.innerHTML = `
          <td>${patient.name}</td>
          <td>${test.name}</td>
          <td>${test.result}</td>
          <td>
            <button class="btn btn-small" onclick="printReport('${patient.name}', '${test.name}', '${test.result}')">
              Print
            </button>
          </td>
        `;

        tableBody.appendChild(row);
      }
    });
  });
}

/* ==============================
   PRINT SINGLE REPORT
============================== */
function printReport(patientName, testName, result) {
  const win = window.open("", "_blank");
  win.document.write(`
    <html>
      <head>
        <title>Lab Report</title>
        <style>
          body { font-family: Arial, sans-serif; padding: 20px; }
          h2 { color: #2c3e50; }
          .report-box { border: 1px solid #ccc; padding: 15px; border-radius: 8px; }
          .footer { margin-top: 20px; font-size: 12px; color: #777; }
        </style>
      </head>
      <body>
        <h2>Medical Lab Report</h2>
        <div class="report-box">
          <p><b>Patient:</b> ${patientName}</p>
          <p><b>Test:</b> ${testName}</p>
          <p><b>Result:</b> ${result}</p>
        </div>
        <div class="footer">
          Generated by MedLab System
        </div>
        <script>window.print();</script>
      </body>
    </html>
  `);
  win.document.close();
}

/* ==============================
   EXPORT ALL REPORTS (JSON File)
============================== */
function initExportButton() {
  const exportBtn = document.getElementById("export-btn");
  if (!exportBtn) return;

  exportBtn.addEventListener("click", () => {
    const patients = JSON.parse(localStorage.getItem("patients")) || [];

    const completedReports = [];
    patients.forEach((p) => {
      p.tests.forEach((t) => {
        if (t.status === "Completed") {
          completedReports.push({
            patient: p.name,
            test: t.name,
            result: t.result,
          });
        }
      });
    });

    const blob = new Blob([JSON.stringify(completedReports, null, 2)], {
      type: "application/json",
    });

    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "lab-reports.json";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  });
}
